version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  publish:
    docker:
      - image: rishabhpoddar/supertokens_android_sdk_testing
    steps:
      - checkout
      - run: ./gradlew clean build -x test bintrayUpload -PbintrayUser=supertokens -PbintrayKey=$BINTRAY_KEY -PdryRun=false
      - slack/status
  test:
    docker: 
      - image: rishabhpoddar/supertokens_android_sdk_testing
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: (cd / && ./runMySQL.sh)
      - run: mysql -u root --password=root -e "CREATE DATABASE auth_session;"
      - run: mysql -u root --password=root -e "set global max_connections = 10000;"
      - run: (cd .circleci/ && ./doTests.sh)
      - slack/status
workflows:
  version: 2
  tagged-build:
    jobs:
      - publish:
          context:
            - slack-notification
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test:
          context:
            - slack-notification
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/