version: 2.1
orbs:
  continuation: circleci/continuation@0.1.2
  slack: circleci/slack@3.4.2
  jq: circleci/jq@2.2.0
jobs:
  test-dev-tag-as-not-passed:
    docker:
      - image: rishabhpoddar/supertokens_website_sdk_testing_node_16
    steps:
      - run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/ # This makes npm use http instead of ssh (required for node 16)
      - checkout
      - run: (cd .circleci/ && ./markDevTagAsTestNotPassed.sh)
  test-unit:
    docker: 
      - image: rishabhpoddar/supertokens_android_sdk_testing
    environment:
      JVM_OPTS: -Xmx3200m
    parameters:
      fdi-version:
        type: string
    steps:
      - run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/ # This makes npm use http instead of ssh (required for node 16)
      - checkout
      - run: apt-get clean
      - run: apt-get purge mysql* -y
      - run: apt-get update
      - run: apt-get install -f
      - run: apt-get upgrade -y
      - run: update-ca-certificates -f
      - run: cd / && wget https://download.java.net/java/GA/jdk15.0.1/51f4f36ad4ef43e39d0dfdbaf6549e32/9/GPL/openjdk-15.0.1_linux-x64_bin.tar.gz
      - run: cd / && mv openjdk-15.0.1_linux-x64_bin.tar.gz /usr/java
      - run: cd /usr/java && tar -xzvf openjdk-15.0.1_linux-x64_bin.tar.gz
      - run: cd / && echo 'JAVA_HOME=/usr/java/jdk-15.0.1' >> /etc/profile
      - run: cd / && echo 'PATH=$PATH:$HOME/bin:$JAVA_HOME/bin' >> /etc/profile
      - run: cd / && echo 'export JAVA_HOME' >> /etc/profile
      - run: cd / && echo 'export JRE_HOME' >> /etc/profile
      - run: cd / && echo 'export PATH' >> /etc/profile
      - run: cd / && update-alternatives --install "/usr/bin/java" "java" "/usr/java/jdk-15.0.1/bin/java" 2
      - run: cd / && update-alternatives --install "/usr/bin/javac" "javac" "/usr/java/jdk-15.0.1/bin/javac" 2
      - run: cd / && update-alternatives --set java $(update-alternatives --list java | grep jdk-15)
      - run: java -version
      - run: (cd .circleci/ && ./doTests.sh  << parameters.fdi-version >>)
  test-success:
    docker:
      - image: rishabhpoddar/supertokens_website_sdk_testing_node_16
    steps:
      - run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/ # This makes npm use http instead of ssh (required for node 16)
      - checkout
      - run: (cd .circleci/ && ./markAsSuccess.sh)
      - slack/status

workflows:
  version: 2
  tagged-build:
    jobs:
      - test-dev-tag-as-not-passed:
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test-unit:
          requires:
            - test-dev-tag-as-not-passed
          context:
            - slack-notification
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          matrix:
            parameters:
              fdi-version: placeholder
      - test-success:
          requires:
            - test-unit
          context:
            - slack-notification
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/